version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: symfony_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  webserver:
    image: nginx:alpine
    container_name: symfony_webserver
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www

volumes:
  db_data:
    driver: local
